use crate::context::LintContext;
use crate::diagnostic::{Diagnostic, Tier};
use crate::lang::CODE_LANGS;
use crate::registry::RuleDef;
use regex::Regex;
use std::sync::LazyLock;

pub static RULE: RuleDef = RuleDef {
    code: "SLOP004",
    name: "AI attribution / chat-share artifact",
    tier: Tier::A,
    langs: CODE_LANGS,
    default_on: true,
    path_gated: false,
    check,
};

static RE_TOOL: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(generated|written|created|authored|suggested)\s+(by|with|using)\s+(chat\s?gpt|gpt-?[345o]?|copilot|claude(\s+code)?|gemini|codex|cursor|bard|llm)\b",
    )
    .unwrap()
});
static RE_SHARE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(claude\.ai/share|chat(gpt)?\.com/share|chat\.openai\.com/share)").unwrap()
});
static RE_OAICITE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r":contentReference\[oaicite").unwrap());
static RE_TURN: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"turn\d+search\d+").unwrap());
static RE_EMOJI: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)🤖\s*generated with").unwrap());

fn check(rule: &'static RuleDef, ctx: &LintContext, out: &mut Vec<Diagnostic>) {
    for c in ctx.comments {
        if c.is_doc {
            continue;
        }
        let hit = RE_TOOL.is_match(c.text)
            || RE_SHARE.is_match(c.text)
            || RE_OAICITE.is_match(c.text)
            || RE_TURN.is_match(c.text)
            || RE_EMOJI.is_match(c.text);
        if hit {
            out.push(Diagnostic::at(
                rule,
                ctx,
                c.line,
                c.col,
                "AI attribution / chat-export artifact in comment",
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_attribution() {
        assert!(RE_TOOL.is_match("// Written by Copilot"));
        assert!(RE_TOOL.is_match("# Created with Claude"));
        assert!(RE_TOOL.is_match("// Suggested by GPT-4"));
        assert!(RE_SHARE.is_match("// https://claude.ai/share/abc123"));
    }

    #[test]
    fn does_not_match_benign_ai_mention() {
        assert!(!RE_TOOL.is_match("// This function uses AI to classify data"));
        assert!(!RE_TOOL.is_match("# Auto-generated by build tool"));
    }
}
