use crate::context::LintContext;
use crate::diagnostic::{Diagnostic, Tier};
use crate::lang::{NatLang, CODE_LANGS};
use crate::registry::RuleDef;
use regex::Regex;
use std::sync::LazyLock;

pub static RULE: RuleDef = RuleDef {
    code: "SLOP004",
    name: "AI attribution / chat-share artifact",
    tier: Tier::A,
    langs: CODE_LANGS,
    natlangs: &[NatLang::En, NatLang::PtBr],
    default_on: true,
    path_gated: false,
    check,
};

static RE_TOOL: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(generated|written|created|authored|suggested)\s+(by|with|using)\s+(chat\s?gpt|gpt-?[345o]?|copilot|claude(\s+code)?|gemini|codex|cursor|bard|llm)(?-u:\b)",
    )
    .unwrap()
});
/// Brazilian-Portuguese twin of `RE_TOOL`. The tool-name alternation is copied verbatim from
/// `RE_TOOL` on purpose: every tool name is a loanword in Portuguese too, so it's the surrounding
/// phrase that differs, not the token.
static RE_TOOL_PT_BR: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(?:(?:gerad|escrit|criad|sugerid|produzid)[oa]s?\s+(?:por|pel[oa]|com|usando|com (?:a )?ajuda d[oa]|com (?:o )?aux[íi]lio d[oa])|de autoria d[oa])\s+(?:o |a )?(?:chat\s?gpt|gpt-?[345o]?|copilot|claude(?:\s+code)?|gemini|codex|cursor|bard|llm)(?-u:\b)",
    )
    .unwrap()
});
static RE_SHARE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(claude\.ai/share|chat(gpt)?\.com/share|chat\.openai\.com/share)").unwrap()
});
static RE_OAICITE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r":contentReference\[oaicite").unwrap());
static RE_TURN: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"turn\d+search\d+").unwrap());
static RE_EMOJI: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)🤖\s*generated with").unwrap());

// RE_SHARE, RE_OAICITE, RE_TURN, RE_EMOJI are language-neutral (URLs and tool-generated tokens),
// so they run unconditionally below rather than being gated on `ctx.natlangs` -- there's no
// Portuguese twin because there's nothing language-specific to translate.
fn check(rule: &'static RuleDef, ctx: &LintContext, out: &mut Vec<Diagnostic>) {
    let en = ctx.natlangs.contains(&NatLang::En);
    let pt = ctx.natlangs.contains(&NatLang::PtBr);
    for c in ctx.comments {
        if c.is_doc {
            continue;
        }
        let hit = (en && RE_TOOL.is_match(c.text))
            || (pt && RE_TOOL_PT_BR.is_match(c.text))
            || RE_SHARE.is_match(c.text)
            || RE_OAICITE.is_match(c.text)
            || RE_TURN.is_match(c.text)
            || RE_EMOJI.is_match(c.text);
        if hit {
            out.push(Diagnostic::at(
                rule,
                ctx,
                c.line,
                c.col,
                "AI attribution / chat-export artifact in comment",
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lang::Lang;
    use tree_sitter::Parser;

    #[test]
    fn matches_attribution() {
        assert!(RE_TOOL.is_match("// Written by Copilot"));
        assert!(RE_TOOL.is_match("# Created with Claude"));
        assert!(RE_TOOL.is_match("// Suggested by GPT-4"));
        assert!(RE_SHARE.is_match("// https://claude.ai/share/abc123"));
    }

    #[test]
    fn does_not_match_benign_ai_mention() {
        assert!(!RE_TOOL.is_match("// This function uses AI to classify data"));
        assert!(!RE_TOOL.is_match("# Auto-generated by build tool"));
    }

    #[test]
    fn matches_pt_br_attribution() {
        assert!(RE_TOOL_PT_BR.is_match("// Gerado por ChatGPT"));
        assert!(RE_TOOL_PT_BR.is_match("# Escrito com o Claude"));
        assert!(RE_TOOL_PT_BR.is_match("// Sugerido pelo Copilot"));
        assert!(RE_TOOL_PT_BR.is_match("// Código de autoria do Gemini"));
        assert!(RE_TOOL_PT_BR.is_match("// Criado com a ajuda do Codex"));
    }

    #[test]
    fn re_tool_pt_br_alternatives() {
        let samples: &[&str] = &[
            "// produzido por ChatGPT",
            "// escrita usando Chat GPT",
            "// criado com o auxílio do GPT-4",
            "// gerados pelo Copilot",
            "// sugerida com a ajuda da Claude Code",
            "// de autoria do Gemini",
        ];
        for s in samples {
            assert!(RE_TOOL_PT_BR.is_match(s), "{s}");
        }
    }

    #[test]
    fn does_not_match_pt_br_benign_ai_mention() {
        assert!(!RE_TOOL_PT_BR.is_match("// Esta função usa IA para classificar dados"));
    }

    fn diagnostics_for_natlangs(src: &str, natlangs: &'static [NatLang]) -> Vec<Diagnostic> {
        let mut p = Parser::new();
        p.set_language(&crate::lang::ts_language(Lang::Ts)).unwrap();
        let tree = p.parse(src, None).unwrap();
        let (comments, strings, index) = crate::context::extract(&tree, src, Lang::Ts);
        let ctx = LintContext {
            display_path: "test.ts".to_string(),
            source: src,
            index: Some(&index),
            lang: Lang::Ts,
            comments: &comments,
            strings: &strings,
            is_test_path: false,
            is_stub_file: false,
            deps: None,
            prose: None,
            natlangs,
        };
        let mut out = Vec::new();
        check(&RULE, &ctx, &mut out);
        out
    }

    #[test]
    fn pt_br_gate_silences_portuguese_panel_when_only_english_selected() {
        let src_pt = "// Gerado por ChatGPT\nfunction f() {}\n";
        assert!(diagnostics_for_natlangs(src_pt, &[NatLang::En]).is_empty());

        let src_en = "// Written by Copilot\nfunction f() {}\n";
        assert!(diagnostics_for_natlangs(src_en, &[NatLang::PtBr]).is_empty());
    }

    #[test]
    fn language_neutral_panels_fire_regardless_of_natlangs() {
        let src = "// https://claude.ai/share/abc123\nfunction f() {}\n";
        assert_eq!(diagnostics_for_natlangs(src, &[NatLang::En]).len(), 1);
        assert_eq!(diagnostics_for_natlangs(src, &[NatLang::PtBr]).len(), 1);
    }

    #[test]
    fn pt_br_panel_fires_through_check_under_default_union() {
        let src = "// Gerado por ChatGPT\nfunction f() {}\n";
        let diags = diagnostics_for_natlangs(src, crate::lang::ALL_NATLANGS);
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].code, "SLOP004");
    }
}
